default:
    phns_len: 61
train1:
    # path
    data_path: '/home/admin/Music/TIMIT/TIMIT/NIST/TRAIN/*/*/*.wav'
    exp_name: 'exp_190121'
    # model
    hidden_units: 128  # alias: E
    num_banks: 8
    num_highway_blocks: 4
    norm_type: 'ins'  # a normalizer function. value: bn, ln, ins, or None
    t: 1.0  # temperature
    dropout_rate: 0.2
    device: 1

    # train
    batch_size: 32
    lr: 0.0003
    num_epochs: 1000
    steps_per_epoch: 500
    eval_interval: 10
    save_per_epoch: 50
    num_gpu: 1
    num_workers: 10

train2:
    data_path: '/home/admin/Music/VCTK/VCTK-Corpus/wav16/p299/train/*.wav'
    exp_name: 'exp_190121'
    # TODO: fix this
    kernel_size: 3
    stride_size: 1
    padding_size: 1
    num_workers: 10
    device: 1

    # train
    num_epochs: 500

eval1:
    data_path: '/home/admin/Music/TIMIT/TIMIT/NIST/TEST/*/*/*.wav'
    exp_name: 'exp_190121'
    num_workers: 10

eval2:
    data_path: '/home/admin/Music/VCTK/VCTK-Corpus/wav16/p299/eval/*.wav'
    exp_name: 'exp_190121'
    num_workers: 10